version: "3.9"

services:

  app-mysql:
    container_name: app-mysql
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysqldb_data:/var/lib/mysql
      - ./docker/mysql_installer/master/master.cnf:/etc/mysql/conf.d/master.cnf:ro
      - ./docker/mysqlseed:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=app_Password
      - MYSQL_PASSWORD=app_Password
      - MYSQL_USER=app_User
      - MYSQL_DATABASE=app
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      interval: 5s
      timeout: 3s
      retries: 10
    logging:
      driver: none
    networks:
      - microservice_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql-rep1:
    container_name: mysql-rep1
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - mysqldb_data_rep1:/var/lib/mysql
      - ./docker/mysql_installer/replicas/replica.cnf:/etc/mysql/conf.d/replica.cnf:ro
      - ./docker/mysqlseed:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=app_Password
      - MYSQL_PASSWORD=app_Password
      - MYSQL_USER=app_User
      - MYSQL_DATABASE=app
    depends_on:
      - app-mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      interval: 5s
      timeout: 3s
      retries: 10
    logging:
      driver: none
    networks:
      - microservice_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql_installer:
    image: mysql:8
    environment:
      - MYSQL_SLAVE_PASSWORD=app_Password
      - MYSQL_MASTER_PASSWORD=app_Password
      - MYSQL_ROOT_PASSWORD=app_Password
      - MYSQL_REPLICATION_USER=replication
      - MYSQL_REPLICATION_PASSWORD=app_Password
      - app_MYSQL_HOST=app-mysql
      - MYSQL_REP1_HOST=mysql-rep1
    depends_on:
      - app-mysql
      - mysql-rep1
    volumes:
      - ./docker/mysql_installer/installer/mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
    networks:
      - microservice_network